# ===================================================================
# Spring Boot configuration for the "test" profile.
# ===================================================================
spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
# ===================================================================
# Application specific properties
# ===================================================================
