# ===================================================================
# Spring Boot configuration for the "test" profile.
# ===================================================================
spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
# ===================================================================
# Application specific properties
# ===================================================================
