# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: luix
services:
  spring-boot-sample:
    image: spring-boot-sample
    container_name: spring-boot-sample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=test
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
    ports:
      - 127.0.0.1:8020:8020
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/management/health"]
      interval: 5s
      timeout: 5s
      retries: 40
